// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASK.Sample.Ajax.Models
{
    public partial class Department
    {
        public int DeptId { get; set; }
        public string DeptName { get; set; }
        public int? ManagerId { get; set; }
        public int? ParentDeptId { get; set; }
    }
}